SQUARE_SIZE = 20
BOARD_SIZE_X = 60
BOARD_SIZE_Y = 30
PADDING = 240

LINE_LENGTH_X = BOARD_SIZE_X*SQUARE_SIZE
LINE_LENGTH_Y = BOARD_SIZE_Y*SQUARE_SIZE
GAME_X = SQUARE_SIZE*BOARD_SIZE_X
GAME_Y = SQUARE_SIZE*BOARD_SIZE_Y
WIN_X = GAME_X + PADDING
WIN_Y = GAME_Y + PADDING
EDGE_X = PADDING/4
EDGE_Y = PADDING/4
GRID_POS = (EDGE_X, EDGE_Y)

DARK_BLUE = (0, 25, 51)
WHITE = (245, 245, 245)
GREY = (200, 200, 200)
BLACK = (0, 0, 0)
BLUE = (0, 128, 255)
GREEN = (0, 155, 0)
LIGHT_BLUE = (0, 255, 255)
YELLOW = (255, 255, 51)
RED = (200, 0, 0)
BUTTON_COLOR = (0, 204, 204)
BUTTON_HIGHLIGHT = (0, 255, 255)
LIGHT_RED = (255, 102, 102)
HIGHLIGHT_RED = (255, 153, 153)

START_COLOR = RED
END_COLOR = GREEN
WALL_COLOR = DARK_BLUE
OPEN_COLOR = LIGHT_BLUE
CLOSED_COLOR = BLUE
PATH_COLOR = YELLOW

VISUALIZATION_COLORS = [OPEN_COLOR, CLOSED_COLOR, PATH_COLOR]

OPTION_LIST = ["Dijkstra", "A Star", "GBF", "Depth First", "Breadth First"]
DROP_DOWN_MENU_COLOR = [BUTTON_COLOR, BUTTON_HIGHLIGHT]
DROP_DOWN_OPTION_COLOR = [LIGHT_RED, HIGHLIGHT_RED]
